version : '3.8'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 22181:2181
  
  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - 29092:29092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  kafka-mysql:
    image: mysql:latest
    container_name: kafka-mysql
    ports:
      - 3309:3306
    environment:
      - MYSQL_ROOT_PASSWORD=11111111
    volumes:
      - kafka-python-app-volume:/var/lib/mysql
      - kafka-python-app-volume-config:/etc/mysql
    networks:
      - kafka-python-app-network
  
  data_drift_backend:
    build: 
      context: .
      dockerfile: src/data_drift_backend/Dockerfile
    container_name: data_drift_backend
    depends_on:
      - kafka
      - kafka-mysql
    ports:
      - 80:80
    networks:
      - kafka-python-app-network

networks:
  kafka-python-app-network:
    name: kafka-python-app-network
volumes:
  kafka-python-app-volume:
  kafka-python-app-volume-config: